<script src="{!! URL::asset('static/web/js/vendor/jquery-2.2.4.min.js') !!}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="{!! URL::asset('static/web/js/vendor/bootstrap.min.js') !!}"></script>
<script src="{!! URL::asset('static/web/js/jquery.ajaxchimp.min.js') !!}"></script>
<script src="{!! URL::asset('static/web/js/owl.carousel.min.js') !!}"></script>
<script src="{!! URL::asset('static/web/js/jquery.nice-select.min.js') !!}"></script>
<script src="{!! URL::asset('static/web/js/jquery.magnific-popup.min.js') !!}"></script>
<script src="{!! URL::asset('static/web/js/jquery.counterup.min.js') !!}"></script>
<script src="{!! URL::asset('static/web/js/waypoints.min.js') !!}"></script>
<script src="{!! URL::asset('static/web/js/main.js') !!}"></script>